### PR TITLE
Resultset improvements for multiquery results

### LINKED ISSUE #94: ResultSet getSeries() doesn't iterate multiple queries
ResultSet's `getSeries()` will return only the first element of the `parsedResults`. https://github.com/influxdata/influxdb-php/blob/master/src/InfluxDB/ResultSet.php#L104

To reproduce:
```
$query .= "SELECT * FROM m;"
$query .= "SELECT * FROM m;"
$query .= "SELECT * FROM m;"
$result = $influxDB->query($query);
print_r($result->getSeries());
```
Instead of return 3 series, it will only return one.

PHP 7.0.19-1

### PR DESCRIPTION
**Pull request by aldas**
1. multiquery 'statement_id' was introduced in 1.2+ version to InfluxDb results. So to support handling multiquery results query index is added to methods. For backwards compatibility first query result is used as default. 

See the difference:
* version 1.2 -> https://docs.influxdata.com/influxdb/v1.2/guides/querying_data/
* version 1.1 -> https://docs.influxdata.com/influxdb/v1.1/guides/querying_data/

Fixes #94

2. Added methods to help customize ResultSet returned from default driver (Guzzle).

### CODE REVIEW

**Comment by aldas** [comment]
I'm using multiqueries quite a lot and current Resultset implementation is very limiting in that way - I need to get raw json string to access additional resultsets other than first one.

File: src/InfluxDB/ResultSet.php [hunk 1]
```diff
@@ -67,8 +76,8 @@ public function getPoints($metricName = '', array $tags = [])
         $emptyArgsProvided = empty($metricName) && empty($tags);
         foreach ($series as $serie) {
             if (($emptyArgsProvided
-                || $serie['name'] === $metricName
-                || (isset($serie['tags']) && array_intersect($tags, $serie['tags'])))
+                    || $serie['name'] === $metricName
```
Comment (thecodeassassin) [inline src/InfluxDB/ResultSet.php]: this extra indent seems unnecessary to me
